### ISSUE TITLE
VSS error on Truecrypt/Veracrypt volumes

### ISSUE THREAD

**Issue by andywits** [tizbac/proxmoxbackupclient_go#31]
When running in Windows, a backup is not created from any folder on Trucrypt/Veracrypt volume:

```
Starting backup of D:\
Creating VSS Snapshot...panic: Snapshots are not supported for drive D:\, err: VSS error: IVssBackupComponents.IsVolumeSupported: VSS_E_UNEXPECTED_PROVIDER_ERROR - The shadow copy provider had an unexpected error while trying to process the specified operation. (0x5653535f455f554e45585045435445445f50524f56494445525f4552524f52202d2054686520736861646f7720636f70792070726f76696465722068616420616e20756e6578706563746564206572726f72207768696c6520747279696e6720746f2070726f636573732074686520737065636966696564206f7065726174696f6e2e)
goroutine 1 [running, locked to thread]:
main.createVSSSnapshot({0xc00000a1b0?, 0xc0000ac030?})
        /home/runner/work/proxmoxbackupclient_go/proxmoxbackupclient_go/win_snapshot.go:83 +0x645
main.main()
        /home/runner/work/proxmoxbackupclient_go/proxmoxbackupclient_go/main.go:110 +0x5aa
```

The official Veracrypt documentation shows that VSS is not supported
( https://www.veracrypt.fr/en/Issues%20and%20Limitations.html ):
`The Windows Volume Shadow Copy Service is currently supported only for partitions within the key scope of active system encryption (e.g. a system partition encrypted by TrueCrypt, or a non-system partition located on a system drive encrypted by TrueCrypt, mounted when the encrypted operating system is running). Note: For other types of volumes, the Volume Shadow Copy Service is not supported because the documentation for the necessary API is not available.`

Perhaps the solution would be to launch without using VSS, but I did not find such an option.

**Comment by tizbac** [comment]
We could add a switch to disable vss , but then you must be 100% sure that
you don't have open files

Il lun 15 lug 2024, 09:21 Andy Wits ***@***.***> ha scritto:

**Comment by andywits** [comment]
Oh, that would be great if you did!
Yes, I understand that checking open files will be my responsibility.
